services:
  backend-server:
    build: ./Server
    environment:
      DATABASE_URL: "postgresql://USER:PASSWORD@ADRESS:5432/DB"
    ports:
      - 3000:3000
    depends_on:
      - postgres-sql
    volumes:
      - ./Server:/srv/termchat


  postgres-sql:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  pg-admin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ""
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - 8080:80
      - 8443:443

volumes:
  pgsql-data: